version: '3'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"

  snake_game:
    build: ./snake_game
    depends_on:
      - api
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix